version: '3.3'
services:
  db:
    image: mysql:5.5.40
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3305:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql/authorization_server/
volumes:
  my-db: