version: '3.3'
services:
  db:
    image: mysql:8.0.29-debian
    restart: always
    environment:
      MYSQL_DATABASE: 'authorization_server'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '3306:3306'
    expose:
      - '3306'